### ISSUE TITLE
Adapt the iSDX test-mt example for using the tou-six topology

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#10]

**Comment by Baloc** [comment]
Got a problem with the Route Server (we got only one running on the topology). There are no update status on the customer's router.
Additionnally, the OpenFlow rules are not applied. I will be looking for mininet initialization, to see if something is blocking at the begining of the test.

**Comment by mcanini** [comment]
@Baloc what you describe seems to be a different issue than what we are trying to obtain here.
The goal of this task is to contribute a topology definition for Mininet and the corresponding config file for the iSDX using the test-mt example of iSDX as the base.
Please see how @TribuneX has created the multi-hop IXP topology in examples/test-mh.
You should create three files for tou-six as follows:
- mininet.cfg
- sdnip.py
- simple_sdx.py

**Comment by Baloc** [comment]
Ok, I followed the same procedure as @TribuneX, and pushed the commit  0328ba1808fcc9d353360f8d897d50dd0032f68f .

**Comment by mcanini** [comment]
@Baloc thank you. Can you please document how to start the topology?
