### ISSUE TITLE
Where to commit code?

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#11]
To which repo do we commit which code? Marco forked iSDX, so do we start to adapt this repo for the ENDEAVOUR architecture? 
So do we commit future code here: https://github.com/h2020-endeavour/iSDX or here https://github.com/h2020-endeavour/endeavour

**Comment by mcanini** [comment]
@TribuneX : it's a very good point. We need to discuss this today.
My feeling would be to attempt to push most of our code into the endeavour repo and simply reuse iSDX as much as we can. However, if necessary, we can modify code inside our forked iSDX repo.

**Comment by mcanini** [comment]
During the sync up, we agree that we will avoid pushing code to the iSDX repo, unless it is a necessary change to iSDX.
Hence, most code will live in the endeavour repository.
