### ISSUE TITLE
Make UMBRELLA impl. work with the iSDX config files and implement the UMBRELLA table

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#15]

**Comment by ederlf** [comment]
Pushed the initial version of a standalone app that comunicates with the iSDX reference controller. For this, I created an iSDX configuration file with elements needed for umbrella.
I showed it to Than  (because it is related to issue  #12). In case of any necessary change, it should not be  hard to change the code used for parsing .

**Comment by mcanini** [comment]
@marchiesa please review whether this format is okay

**Comment by marchiesa** [comment]
Great work! It seems to me the only difference is that in the config file there should be just one entry for each participant and not one entry per participant's port. I can fix that, unless there is a specific reason for having it.

**Comment by mcanini** [comment]
@ederlf see @marchiesa question

**Comment by ederlf** [comment]
He is right. I did not noticed they were the same.  
However, on the topology, they are two different routers. Not sure if it is possible at the IXP. We better ask @TribuneX.

**Comment by thanh-nguyen-dang** [comment]
@ederlf : in config file, you have something: "Peers": ["a1", "b2"] for entry c1 and c2 of participants list. But there is no "b2" entry

**Comment by mcanini** [comment]
@TribuneX your inputs kindly requested

**Comment by TribuneX** [comment]
Let me recap: The question is if we can have a participant with two ports, where each port is connected to a different edge switch. Then the answer is yes! However, I am not sure yet how this influences the config file scheme regarding ports and participants.

**Comment by ederlf** [comment]
Thanks @TribuneX! Do you know if they can also have different policies for
different ports? Does it make sense?

**Comment by TribuneX** [comment]
I would say we should support that to allow participants to configure their ports as they were from different participants. A policy could be something like please only send me this kind of traffic (HTTP) to only this port correct? @ederlf @marchiesa

**Comment by ederlf** [comment]
I like this idea too. To handle ports in different colocations as an
individual participant.
The only thing I do not know is how much it would impact iSDX. For example,
how much is the participant AS number
related to the policy handling in the fabric? Would be a problem if they
are binded.

**Comment by marchiesa** [comment]
@ederlf @TribuneX  iSDX can handle policies at the per-IXP-member-port granularity so this is perfectly fine but we need to keep the same structure of the "sdx_global.cfg" config file that is currently used in the iSDX. Namely, each "participant" item contains a list of its ports. The policies of all the participant's ports are defined in its "participant_x.py" file.

**Comment by marchiesa** [comment]
@ederlf  @TribuneX After discussing with the iSDX developers, I understood that each participant can indeed specify its inbound policies at the per-port level of granularity. However, outbound policies are shared among all the ports of a single participant. That is, we cannot have different outbound policies for different ports of a single participant.  I would suggest to stick with the structure of the current "sdx_global.cfg" configuration file and leave the job of improving outbound policies to the iSDX developers. By the way, @TribuneX , can you imagine any practical use case in which a participant would like to have different outbound policies for each of its ports?

**Comment by mcanini** [comment]
@marchiesa Sounds good to me.

@ederlf Can we close this issue? Has anyone performed testing of this new code?

**Comment by ederlf** [comment]
It can be closed. The code, so far, sends flows to the refmon module of
iSDX., but refmon cannot does not accept
topologies different than the ones already define. Just start to work on
this, so it can accept a multi-hop topology.
I will open a new issue for the task i'm currently working.

**Comment by mcanini** [comment]
@ederlf perfect!
