### ISSUE TITLE
Mininet topologies to use the sdx_global.cfg

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#18]
Adapt the simple_sdx.py of each example to use the information defined in the sdx_global.cfg to keep the topology consistent with the configuration

**Comment by TribuneX** [comment]
Will check again if there still any static simple_sdx.py

**Comment by rbirkner** [comment]
You should take a look at sdx_mininet.py and mininet.cfg at [iSDX-Repo](https://github.com/sdn-ixp/iSDX/tree/master/examples/test-ms/mininet). It is probably not exactly what you want but already a step closer than the simple_sdx.py.

**Comment by TribuneX** [comment]
Thanks. So [sdx_mininet.py](https://github.com/sdn-ixp/iSDX/blob/master/examples/test-ms/mininet/sdx_mininet.py) is actually a successor of [simple_sdx.py](https://github.com/sdn-ixp/iSDX/blob/master/examples/test-ms/mininet/simple_sdx.py) correct?

**Comment by rbirkner** [comment]
Correct. We realized that it is too complicated to use the hardcoded topology in simple_sdx.py for testing.

**Comment by TribuneX** [comment]
@rbirkner Seems that sdx_mininet.py is not needed any more. At least it was deleted with this [commit](https://github.com/sdn-ixp/iSDX/commit/90e98d24da1bd344c78846e84ba63106d2317ff6)
Any plans at the iSDX team to handle consistency now?

**Comment by rbirkner** [comment]
sorry for the delay. I don't know why it was deleted. The ongoing development focuses more on the hardware deployment and making the code more reliable. The two examples test-ms and test-mt were only used by me to test it. Now, they do more sophisticated [regression testing](https://github.com/sdn-ixp/iSDX/tree/master/test) and generate topologies.

**Comment by TribuneX** [comment]
Will be obsolete as soon as we use torch for setting up the example topology

**Comment by TribuneX** [comment]
Will be obsolete as soon as we use torch for setting up the example topology
