### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#19]
I am attempting to go through the instructions on https://github.com/h2020-endeavour/endeavour/raw/master/README.md and they are not working.

**Comment by mcanini** [comment]
@ederlf Similarly, the instructions on https://github.com/h2020-endeavour/endeavour/raw/master/examples/test-umbrella/Readme.md seem to be broken at the moment

**Comment by ederlf** [comment]
Can I have more details about the first case? What exactly is not working?

**Comment by mcanini** [comment]
@TribuneX this appears to be related to your changes. can you please fix the README files?
