### ISSUE TITLE
Adapt simple_sdx.py to make use of the information in sdx_global.cfg

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#20]
1. create a configuration similar to https://github.com/h2020-endeavour/endeavour/blob/master/examples/test-mh/config/sdx_global.cfg
2. Use the information from this config file to setup the topology similar to
   https://github.com/h2020-endeavour/endeavour/blob/master/examples/test-mh/mininet/simple_sdx.py

**Comment by mcanini** [comment]
@Baloc this is similar to the work done by @TribuneX on #18

**Comment by TribuneX** [comment]
Will be obsolete as soon as we use torch for setting up the example topology
