### ISSUE TITLE
Add edge switch id to participant port

### ISSUE THREAD

**Issue by ederlf** [h2020-endeavour/endeavour#21]
It can make it easier to access this information (otherwise would need to parse the whole fabric connections)
https://github.com/h2020-endeavour/endeavour/blob/master/examples/test-mh/config/sdx_global.cfg#L127

Something like this. We could add the switch id or the dp_id

```
 "Ports": [
            {
                "Id": 5,
                "MAC": "08:00:27:89:3b:9f",
                "IP": "172.0.0.1"
                "edge": dp_name || dp_id
            }
```

One more thing, gigging through the iSDX code I am finding harder and harder to not make changes to the original. Maybe we will have to go for these changes.

**Comment by TribuneX** [comment]
Seems like a reasonable change. Any obstacles?

**Comment by ederlf** [comment]
I am already considering it :)
It there are no objections I will push it this week.
