### ISSUE TITLE
Doubt about the input table

### ISSUE THREAD

**Issue by ederlf** [h2020-endeavour/endeavour#24]
Do you have an idea why do they use a set_field here? 

```
priority=5,in_port=3 actions=set_field:08:00:27:89:3b:9f->eth_src,go o_table:1
```

The paper says:

```
When the packet enters the IXP fabric, the input table matches on the packet’s incoming port and rewrites the source MAC address to indicate that the packet arrived from AS A (“SRC_A”). If A has an outbound policy, the packet will match on (“SRC_A”), and the outbound table will apply  an outbound policy.
```

Rewriting here seems superfluous, since the src MAC coming from port 3 will be already the one from the participant. 
Is there a case when the MAC src is not from the participant?

**Comment by mcanini** [comment]
Good question!
@agupta13: can you please shed some light on this?

**Comment by marchiesa** [comment]
@ederlf I agree with you. It seems to me that the incoming port is already sufficient for identifying a participant. I am not sure about this rewriting.

**Comment by rbirkner** [comment]
We rewrite the src mac to specify the participant from which the packet is coming from. In case a participant has only a single port, this rewrite is useless. If a participant has multiple ports then the mac address of all the packets is changed to the mac address of the first port of that participant. This rewrite allows us to reduce the number of rules in the outbound table.
