### ISSUE TITLE
Advanced Blackholing as a policy integration

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#27]
Integrate advanced blackholing functionality to easily allow participants to specify filtering rules based on available iSDX policy

Sub-issue to #38

**Comment by mcanini** [comment]
@Baloc I think we might be able to do this by simply using Torch. Please see the docs at https://github.com/sdn-ixp/iSDX/tree/master/test

**Comment by TribuneX** [comment]
@Baloc Was there any progress here? Otherwise, DE-CIX will look into the capabilities of the iSDX policy language for the purpose of Advanced Blackholing.

**Comment by TribuneX** [comment]
Current status: Drop mechanism is missing. We will coordinate with the iSDX developers on their current plans to integrate drop rules.

**Comment by TribuneX** [comment]
Status from Rick on this: 
1. drop action is not yet implemented -> we integrated that in the branch [advanced_blackholing#27](https://github.com/h2020-endeavour/iSDX/tree/advanced_blackholing%2327)
2. dynamic policy updates are not yet supported. There is pseudo code on who to do that [here](https://github.com/h2020-endeavour/iSDX/blob/advanced_blackholing%2327/pctrl/participant_controller.py#L268-L307) -> we are looking who to integrate this for a demo scenario
