### ISSUE TITLE
Startup script

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#28]
Create an easy to execute startup sImilar to [launch.sh](https://github.com/sdn-ixp/iSDX/blob/master/launch.sh)
- Start required modules within its own screen
- Ease the setup for testing

**Comment by ederlf** [comment]
@thanhucl I have a suggestion for the file:
https://github.com/h2020-endeavour/endeavour/blob/master/tm-launch.sh

Can you make the test variable?
e.g:

```
tmux new-window -t $session_name:1 -n 'logserver' "launch.sh test-mh 1"
```

Could be

```
tmux new-window -t $session_name:1 -n 'logserver' "launch.sh $1 1"
```

So we can be able to run any test topology with the script.

**Comment by thanh-nguyen-dang** [comment]
ok Eder, I will do it

**Comment by thanh-nguyen-dang** [comment]
the script is done with the parameter for test case

**Comment by thanh-nguyen-dang** [comment]
error message raised when running test-mh
simple_sdx.py: error: too few arguments

**Comment by mcanini** [comment]
@thanhucl Please add a check to test the presence of the parameter to the script

**Comment by mcanini** [comment]
@thanhucl Please document how to use this script in the README.md file

**Comment by thanh-nguyen-dang** [comment]
added the test for the presence of the parameter and a paragraph describing how to run the script in endeavour/README.md file

**Comment by mcanini** [comment]
@thanhucl thanks for updating the docs. Can you also please describe in the README.md file what is expected from running the script?
There is a bunch of virtual terminals that are opened and it is not clear what is doing what.

**Comment by mcanini** [comment]
@thanhucl This issue is still open because the docs are lacking the description I referred to above

**Comment by TribuneX** [comment]
I will add some documentation for this script
