### ISSUE TITLE
Remove ARP switch from mininet topology

### ISSUE THREAD

**Issue by ederlf** [h2020-endeavour/endeavour#29]

**Comment by TribuneX** [comment]
@ederlf I removed the arp switch in the test-mh topology and connected the arp_proxy to edge1. Can you check the [branch](https://github.com/h2020-endeavour/endeavour/tree/remove_arp%2329) if it works with your current code?

**Comment by ederlf** [comment]
Hi, It works. 
What do you think about adding a default config file for the test, that points directly to the test config folder? Would be nice to speed up things when you do not want to choose a different path for the configuration file.
