### ISSUE TITLE
How to visualize the blackholing and load balancing use cases

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#35]

**Comment by mcanini** [comment]
Consider using http://grafana.org/

**Comment by mcanini** [comment]
@Baloc what is the alternative to grafana you used?

**Comment by Baloc** [comment]
I used this solution for TouIX : http://www.highcharts.com/stock/demo
The main issue is this is not an all-in-one solution, it is only for visualizing data.
I think it would be quicker to try to integrate Grafana for iSDX.

**Comment by ederlf** [comment]
Since the visualisation in Grafana is available from the iSDX guys, now it is a matter to create the queries, on the dashboard, to show what we need.
