### ISSUE TITLE
Create visualisations on Grafana's Dashboard

### ISSUE THREAD

**Issue by ederlf** [h2020-endeavour/endeavour#37]
Take a look on http://graphite.wikidot.com/faq

**Comment by TribuneX** [comment]
How to store Grafana dashboards persistently to have it shared across the participants. Does somebody know an easy way to load exported dashboards by default?

We stored our blackholing dashboard [here](https://github.com/h2020-endeavour/iSDX/blob/blackholing_demo/test/blackholing_demo_dashboard.py). This file can be manually loaded into Grafana. Would be nice if Grafana loads it by default.

**Comment by ederlf** [comment]
@TribuneX   We can follow the procedure described here:
https://github.com/h2020-endeavour/iSDX/tree/master/visualization

"You can easily change them or add other graphs. If you save changes to the Grafana configuration, they are stored in Grafana's SQLite database, /var/lib/grafana/grafana.db. You can dump the database with the command: sqlite3 /var/lib/grafana/grafana.db 'dump'. If you want to commit this database to the SDX repo, save the output of the above command to iSDX/setup/grafana-init.sql. This file is used to initialize the database when the vagrant machine is provisioned."

**Comment by TribuneX** [comment]
Thanks @ederlf That was simple!
