### ISSUE TITLE
Merge mh-ctrl with mh-ctrl_load_balacning with the master in iSDX

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#50]
Check the diffs and try to merge the latest code into the master of iSDX

**Comment by TribuneX** [comment]
I did the following here:

```
git checkout mh_ctrlr_load_balancing
git pull
git checkout master
git pull
git merge mh_ctrl_load_balancing
git push
```

I assumed there will be a commit message reflecting the merge in the commit log of the master. But that is not the case.  Anyway, I assume the code from the branch 'mh-ctrlr_load_balancing' is now in the master?

**Comment by mcanini** [comment]
Looks right to me and there are no differences between branches now. I will delete mh_ctrl_load_balancing
