### ISSUE TITLE
Open question regarding a specific flow rule

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#51]
How has an idea of what the purpose of the flow rule with cookie 0x35 in table 0 is? 
https://github.com/h2020-endeavour/endeavour/blob/master/docs/iSDX-tables.md

**Comment by TribuneX** [comment]
Seems that it is related to the VNHs here: https://github.com/h2020-endeavour/endeavour/blob/b6aa4ed0f706f4d83b30a61fbea24020067c3662/examples/test-mh/config/sdx_global.cfg#L106

Can somebody shortly explain the purpose of it?

**Comment by rbirkner** [comment]
We used to have such a rule to intercept all ARP requests that concerned a VNH and directly send it to the arp proxy.

**Comment by ederlf** [comment]
The purpose is as @rbirkner said, send the ARP request to a VNH directly to the ARP proxy. The flow rewrites the destination MAC as the ARP proxy MAC and then sends it to the load balance/umbrella table to handle the path it should take in the fabric.

@TribuneX ,if your doubt is solved, I think we can close this issue.
