### ISSUE TITLE
Load Balancing matching

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#52]
Request from Marco:
I think that using the least significant bit of both the source and destination should give the better results, as it should be more oblivious to any locality in traffic patterns.

**Comment by Floknation** [comment]
Done and pushed in origin/master. The Setup Tests work fine.
Extract from flow table 4:
nw_src=0.0.0.0/0.0.0.1,nw_dst=0.0.0.1/0.0.0.1 actions=write_metadata:0x10/0xffffffff,goto_table:5
nw_src=0.0.0.1/0.0.0.1,nw_dst=0.0.0.0/0.0.0.1 actions=write_metadata:0x20/0xffffffff,goto_table:5
nw_src=0.0.0.0/0.0.0.1,nw_dst=0.0.0.0/0.0.0.1 actions=write_metadata:0x30/0xffffffff,goto_table:5
nw_src=0.0.0.1/0.0.0.1,nw_dst=0.0.0.1/0.0.0.1 actions=write_metadata:0x40/0xffffffff,goto_table:5
arp actions=write_metadata:0x40/0xffffffffff,goto_table:5
priority=0 actions=CONTROLLER:65535
