### ISSUE TITLE
Support dynamic updates

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#53]
Implement dynamic policy updates.

**Comment by TribuneX** [comment]
@rbirkner I am currently looking into the [pseudo code](https://github.com/h2020-endeavour/iSDX/blob/master/pctrl/ss_rule_scheme.py#L215-L265) which was intended to support dynamic updates of policies. 

It looks pretty complex though. I am a little but puzzled about what the supersets are used for. Do you have a hint where to start looking at?

**Comment by TribuneX** [comment]
@rbirkner Related to that we are also trying to figure out if there is already some sort of client code available as a sketch which is supposed to send policy updates to the participant controller, since the receiver side seems to be implemented: [process policy event](https://github.com/h2020-endeavour/iSDX/blob/advanced_blackholing%2327/pctrl/participant_controller.py#L275-L279)

**Comment by rbirkner** [comment]
The supersets is the name of our encoding scheme. We encode in the destination MAC address two pieces of information: 
(1) all participants at the ixp which could and are willing to handle this packet. This information is used to determine whether an outbound policiy (i.e., match(tcp_dst_port == 80) >> fwd(D)) should be applied. If D is not willing to handle a certain packet, the outbound policy should not be applied.
(2) the BGP best path next hop. This is just an identifier for the default next hop.

@TribuneX Let me know if you need more information about it.

We always talked about implementing it, but haven't found the time to do so. There is no sender side implementation that I know of. There is only an interface for the ARP and BGP proxy, but not for a policy sender.

**Comment by TribuneX** [comment]
Thanks @rbirkner! Rüdiger kindly send me an additional documentation on [supersets](https://docs.google.com/document/d/1BQX8t0HBc1tXuK1G52c-7JE4QudUa3n6mKT_Z3kSSms/edit#)

**Comment by TribuneX** [comment]
We implemented a basic integration of policy insertion and removal from within a Torch spec file:
[blackholing example spec](https://github.com/h2020-endeavour/iSDX/blob/advanced_blackholing_new%2327/test/specs/test1-mh-bh.spec#L39-L45)

It does not yet allow to remove policies which are bounded to a certain VNH
