### ISSUE TITLE
Values in influx db

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#58]
Seems that not all ports are relflected in the influx db. 

```
influx -database sdx -execute 'show series'
```

only lists:

```
port_bytes_out,dp_name=Edge-1,port_name=A
port_bytes_out,dp_name=Edge-1,port_name=Arp\ Proxy
port_bytes_out,dp_name=Edge-1,port_name=LOCAL
port_bytes_out,dp_name=Edge-1,port_name=Route\ Server
port_bytes_out,dp_name=Edge-1,port_name=core\ 1
port_bytes_out,dp_name=Edge-1,port_name=core\ 2
port_bytes_out,dp_name=Edge-1,port_name=core\ 3
port_bytes_out,dp_name=Edge-1,port_name=core\ 4
```

Seems that we only have the ports for Edge-1?

**Comment by ederlf** [comment]
It depends on the configuration files created for the test. How is the
gauge configuration in the example?

**Comment by TribuneX** [comment]
I copied the configuration files from here, since the topology is the same: https://github.com/h2020-endeavour/endeavour/tree/master/examples/test-mh/config

**Comment by TribuneX** [comment]
I am running the setup with torch:

```
sudo bash startup.sh --stats test2-mh-bh
```

**Comment by ederlf** [comment]
Found out that it is because
https://github.com/h2020-endeavour/endeavour/blob/master/examples/test-mh/config/gauge.conf
lists
only the edge-1 config file.
We have to list all dps to be monitored.

Maybe should define some fixed configs and maybe try to generate it from
torch?

**Comment by TribuneX** [comment]
[Fixed it](https://github.com/h2020-endeavour/endeavour/commit/8642b3451d44a256c9a1569d0037613cfd0263cc)
