### ISSUE TITLE
Forwarding rule to in- and outbound table

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#60]
A certain flow rule is only generated an installed in table 0 (main-in) if a certain participant has either an in- or outbound policies.

See this flow rule:

```
cookie=0x1, duration=116.479s, table=0, n_packets=3, n_bytes=218, priority=5,in_port=5 actions=set_field:08:00:27:89:3b:9f->eth_src,goto_table:1
```

Does somebody know where this flow rule is generated and send to the central controller within the iSDX code? Since it is not done when we only install blackholing policies. I wanna extend it to also install this default forwarding rule when a blackholing policy is used.

**Comment by ederlf** [comment]
@TribuneX , this flow is created on the following piece of code:
https://github.com/h2020-endeavour/iSDX/blob/master/xctrl/gss.py#L152
