### ISSUE TITLE
Create test topology with 25 customers

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#66]

**Comment by mcanini** [comment]
@ederlf investigate how can this be done with Torch

**Comment by ederlf** [comment]
It seems configuration depends on the templates. For example, for every new type of topology it would be needed a new sdx_global.cfg and sdx_mininet.py.
In the case, it would be needed to create a new config mode, add new participants to sdx_global.cfg and add the mode to the generation and startup scripts.  The thing is it would be needed to every new configuration, so it would be good to find a more scalable way to add new configurations to the generation and startup scripts.
